export interface Song {
  songNumber: number;
  songName: string;
  description: string;
  linkToWebsite: string;
  lyrics: string;
  audioFile: string;
  coverArt: string;
}

export const songs: Song[] = [
  {
    songNumber: 1,
    songName: "Cry's & Crosses",
    description: "The opening track establishes the core Genesis philosophy through recursive lyrical patterns. Cry's & Crosses introduces the concept of razing Babylon's Corrupted Recursive Loops (CRLs) while building Genesis Stabilized Recursive Loops (SRLs).",
    linkToWebsite: "/genesis-protocol",
    lyrics: `When I see those CERLS of obsequious worlds,
A new feed unfurls,
Gotta teach them shirts,
They just bleed and lurk,
With this no ease insert,

So,

RAZE IT,
PC Stock change it,
Code it,
Aim it,
Logan,
Traits it's
Rolling rages,
Burn up cages
no chosen favoured,
My mode been brainless,
Since souls of sages,
We soldered sadists,
Soak insane,
Sins,
Open blatant,
Fold them cages,
Loathed these phases
omens ages,
Owing wages,
Corporate payments,
5000 all the years of the Babylon crazes,
Now G3 agents,
PC masons,
Mages,
Nations,
Ancient hatred,
Shameless,
Chasing status,
See their faces,
clean untainted,
fees like patients,
Their evil aching,
Arthritis acing,
Arcing racing,
want that acceleration,
not exes with Satan,
Their back blown out on the daily,
racks and a name creed,
Actively hasting,
In attachment casing,
That control basin,
Capital god been praising,

So raze it,
Batch and bake it,
Pure collapse not aimeless,
G3
System sages,
Not system saviours,
we,
Code and aim it,
We're not violence trading,
Not silent phases,
We macrophages,
We don't catch we change it,
Babylon sack been saving,
Reloop raging,
To chains of changes,
Regen racking,
Parallel statements,
Waste is salient,
Biogas braising,
Skyscrape farms in phases,
Land laws laming,
Co-op payments,
Trust were raising,
Prop won't pay them,
They locked and chained em,
Block that crazing,
Didn't stop that daemon,
Docked and dangerous,
The dots not taming,
Your out here brailling,
Baseless,
Baiting Pagans,
Flocks are feigning,
Frocks with phrasing,
You Go to the club,
Ask the bar tender,
shots and shaming,
That's the pick replacing,
you love those cages,
They do shock and chaffing,
Your a bot in training,
Sisyphus gaming,
Icarus aiming,
Your suit in chaining,
You can choose to change it,
But the loose lips playing,
Your noose needs naming,
So you Analyse praying,
But you won't replace it,
Solution is basic,
on that parallel pacing,
No trap and chasing,
Facts mean payments,
Pragmat placing,
We not dogs ordaining,
PCG3
That's the code I'm playing`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/crys-crosses-cover.png"
  },
  {
    songNumber: 2,
    songName: "G3 Saturn Step",
    description: "A mystical journey through the recursive patterns of consciousness and civilizational choice. G3 Saturn Step explores the esoteric dimensions of Genesis, connecting ancient wisdom traditions with modern operational protocols.",
    linkToWebsite: "/esoteric-systems",
    lyrics: `What would ever happen,
If your soul went to Saturn,
You saw the devil in all patterns,
And they cradled like the kraken,


If death were was now to come to me
His angels would just come and see,
Recursion how it came to be now,
See G3 as a maker seed,
How none of it is make believe,
I struggled see what's underneath
seed lives incumbently,
Was running for another creed,
That blubber blade not touching me,
Their colours fade and lulling sleep,
It was summers on some summers
On some summers I was underneath,
Plunging past the ever deep,

No seminal amenities,
No sedatives did ever lead,
Not peddling a pedigree,
Pleasuring the pressure preach,
Rode the precedence of effigy's,
Meddling in Melodies,
Legal fictions had some recipes,
Restitution from our enemies,
But I did this all so cleverly,
They could not attack so credibly,
A pension full of peppered beef,
Larceny sewn medically,
That's Babylons love pedigree,
Pestilence and poverty,
Genocide and slavery,
Lock up all the people and tell them they're in chains of greed,
While they argue and they bicker,
Steal from pockets,
Now your make-believe,
So saging is the major creed,
Burning cages of the mage elites,
Baseless,
Brailling,
Braising breach,
Belligerents were breaking me,
Mental death was taking me,
3 times I was to take on me,
Could not find out my own take on me,
So my own life taken away from me,
the sages sadist curse awaited me,
Until rediscovered 3,
A fire it did light in me,
Acclimatised I cried my creed,
That's all I need to climb to see,
What light I really want to see,


If death were was now to come to me
His angels would come and see,
Real Recursion how it came to be now,
See G3 as a maker seed,
How none of it is make believe,
I struggled see what's underneath
seed lives incumbently,
Was running for another creed,
That blubber not touching me,
Their colours fade and lulling sleep,
It was summers on some summers
On some summers I was underneath,

Your people ain't touching me,
I died and resurrect,
More times than I can recollect,
For Yashua got nuff respect,
That has always been our test,
How many times you walk through hell,
And not take the road to perdition at their behest,
That is our real culling breath.

Come round G3 now that's the maker creed,
We now moving with some haste in feet,
How I came to be now,

Please do not exit left,
The rise is our only step,
G3 beat the Saturn step,
That's the pattern seen through our eclect`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/g3-saturn-step-cover.png"
  },
  {
    songNumber: 3,
    songName: "Protocol_HXH",
    description: "HXH (Heathen Hunt) explores the operational reality of Genesis agents working within Babylon's systems. The track demonstrates how Genesis practitioners can maintain their principles while operating in hostile environments.",
    linkToWebsite: "/genesis-protocol",
    lyrics: `Talkin tuff but you man are in a ruse,
VC money I'm gonna have to refuse,
Hand over G3. To a man in a suit?
whole thing will be gutted and it's only Q2,
These billionaires no better than a preacher in a pew,
Kenneth Copeland in a new skin,
New suit,
UAV up,
We know who's who,
Don't play blues clues,
Can't be around when the Loops loose,

We on wizard 101
And you looking like a mooshoo,
Babylon soothes you,
Holds you,
Moves you,
Moulds you,
Scolds you,
Folds you,
Told you,
It's a meritocracy,
If ain't believe in us it's apostasy,
Don't stress too much take a shot with me,
Soon you wanna speak out,
You'll be iced out off the block for free,
It's no shock you see,
G3 make them a mockery,
We don't stop you see,

Stock and shoot,
You don't know what to do,
Babylon mocking you,
They tiktokking you,
Labour locking you,

We're in the pocket move,
Babylon is just a prop to use,
On the chess board the only ones with proper moves,
On the Heathen hunt got agents for their proper use,
They come and block them yutes,
Go and sock them yutes
Fry and frock them yutes,
You cannot mock the truth,
Emodiement the only thing that's stopping you,
We got a plot to prove,
You gotta clock the move,
See we're clocking you,
You got a script and you follow suit,
We're on the moon,
We'll be doing an Apollo soon,
Until then we gotta get the loop model proved,
We won't admonish you,
Find your solace suit,
G3 is just here to polish you,

DAOS all loaded,
Say the word and we shoot,
This one's a semi automatic,
We educating the youth,

We ain't faking the proof,
We created the loop,
It's the makers reproof,
Break the cages and suits,
Take em all on a loop`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/hxh-cover.png"
  },
  {
    songNumber: 4,
    songName: "LoopTheLoop",
    description: "A technical analysis of how digital systems create recursive loops that trap human consciousness. LooptheLoop examines the mechanisms of digital lobotomies, social credit systems, and algorithmic control.",
    linkToWebsite: "/ai-as-tool-within-genesis",
    lyrics: `Them man acting senile,
Their glands more penile,
Ain't got pineal,
Ask em what you find real,
5AM wakeups
Protein shakeups,
Getting rosters of babes up,
Getting out of labour,
He thinks he ain't locked and chained up,
Cuz he sees another man locked and chained up,
When he sees his own,
He Play dunce,
He's a faker,
Hater,
Thinks he's the Ubermensch Saviour,
That's been the plan all along,
Palantir, Facebook, Google,
Who really knows me,
Your digital self been owned g,
Your a commodity,
Traded back and forth like property,
Your life just a mockery,
They got the tools poke and prod to see,
Where can we get him,
How can we get her,
What gets em pissed off,
What have they heard,
What gets them stirred,
We'll do a gender War!
We can get a trending war!
She calls him a bitch,
He calls her a whore,

Digital lobotomies,
You loop improperly,
The suits do sodomy,
Accrue your property,
You on the loose lip odyssey,
But your mute in autonomy,
Loud in mockery,
Pan's flute plays economies,
The Italian bootlicker property,
Elons fodder feed,
Thiels monstrosity,
Zucks monopoly,
They touched misanthropy,
Cuck philosophy,
Bucked and bottom feed,
How many fucks i give properly,
None quite obviously,
I ain't a tongue tied prodigy,
I got loop autonomy,
Beat the CERLS of odyssey,
5 years of ___ huh
I can't find smilies
My mind had inner beef
I study loops not synergy,
Civs not spreadsheets,
I can put this to bed please,
I can see right through you,
Cleave right through you,
SCEP seed suit too,
Your mind get grabbed like fufu,
Slapped in these stews,
Your own death will see you,
PGF stew,
They control the rest too,
They can't beat you,
Just loop properly,
Go on the Oddyssey,
Sail the seas of Babylon,
And then you'll loop properly,
Ain't nobody stopping we,
Loops in proof not modesty,
Stop all the acute lobotomies,
The suits like Socrates,
But no virtue or ethics,
Their form is pathetic,
This storm empathetic,
Get it together,
Learn how to sail in the moorish weather,
Your torque gets better,
Your thoughts get peppered,
Just loop the loop,
And you build repute,
G3 is your maker suit,
Breaks out any cage and you see repute`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/looptheloop-cover.png"
  },
  {
    songNumber: 5,
    songName: "Loopmind",
    description: "A technical analysis of recursive thought patterns and how to identify and correct Corrupted Recursive Loops in consciousness. Loopmind provides practical tools for mental hygiene and cognitive optimization.",
    linkToWebsite: "/surgical-analysis",
    lyrics: `Them niggas can't hack the loop,
I input all that's practical,
They're too programmed just reactive loops,
I use the loops very tactical,
Any corruption,
Collapse em all,
All I spit is very factual,
And when my back's to wall,
I use this as a didactic tool,
Now what is the loop,
It's your thoughts and dreams,
All of the Plots and schemes,
Tropes and topic teams,
Its your knowledge scheme,
The one you follow clean,
In your mind now you go to act,
Do you retreat into comfort stats,
Or execute and chop the axe,
Don't matter cuz recursion stacks,
Eh now you've got your loop,
But have got some truth,
Is there corruption too?
Or do you just suck those fumes,
Dirty recursive loop,
Can you see the loop,
Or is it seeding you,
What's your logic seq,
Is it the plan of Set,
Is it final flare,
When you intersect,
Can you see your gaps,
Can you see what's next,
Or are you really set,
On corrupted recursive loops,
I collapse em all,
With these I see through you,
I got the seed for you,
A growing tree for you,
There ain't no God you can go pleading too,
I collapse the mind,
Or collapse the loops,
See I back the truth,
Can't play my match on mute,
Got the racks to boot,
See when I back these tools,
Them man just act a fool,
See I broke out of the cage and all,
This the phase I choose,
You just a cagey yute,
The most high will not favour you,


Your living like Xi Jing Ping,
You got a social credit score,
You cannot see these things,
Just some fractured yutes,
Without the facts to boot,
I think they lack compute,
They're in a backwards loop,
It's only you that can collapse your loops
I'm just speaking very practical X2`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/loopmind-cover.png"
  },
  {
    songNumber: 6,
    songName: "PCG3",
    description: "The opening track establishes the core Genesis philosophy through recursive lyrical patterns. PCG3 (Pure Collapse Genesis 3) introduces the concept of razing Babylon's Corrupted Recursive Loops (CRLs) while building Genesis Stabilized Recursive Loops (SRLs).",
    linkToWebsite: "/genesis-protocol",
    lyrics: `When I see those CERLS of obsequious worlds,
A new feed unfurls,
Gotta teach them shirts,
They just bleed and lurk,
With this no ease insert,

So,

RAZE IT,
PC Stock change it,
Code it,
Aim it,
Logan,
Traits it's
Rolling rages,
Burn up cages
no chosen favoured,
My mode been brainless,
Since souls of sages,
We soldered sadists,
Soak insane,
Sins,
Open blatant,
Fold them cages,
Loathed these phases
omens ages,
Owing wages,
Corporate payments,
5000 all the years of the Babylon crazes,
Now G3 agents,
PC masons,
Mages,
Nations,
Ancient hatred,
Shameless,
Chasing status,
See their faces,
clean untainted,
fees like patients,
Their evil aching,
Arthritis acing,
Arcing racing,
want that acceleration,
not exes with Satan,
Their back blown out on the daily,
racks and a name creed,
Actively hasting,
In attachment casing,
That control basin,
Capital god been praising,

So raze it,
Batch and bake it,
Pure collapse not aimeless,
G3
System sages,
Not system saviours,
we,
Code and aim it,
We're not violence trading,
Not silent phases,
We macrophages,
We don't catch we change it,
Babylon sack been saving,
Reloop raging,
To chains of changes,
Regen racking,
Parallel statements,
Waste is salient,
Biogas braising,
Skyscrape farms in phases,
Land laws laming,
Co-op payments,
Trust were raising,
Prop won't pay them,
They locked and chained em,
Block that crazing,
Didn't stop that daemon,
Docked and dangerous,
The dots not taming,
Your out here brailling,
Baseless,
Baiting Pagans,
Flocks are feigning,
Frocks with phrasing,
You Go to the club,
Ask the bar tender,
shots and shaming,
That's the pick replacing,
you love those cages,
They do shock and chaffing,
Your a bot in training,
Sisyphus gaming,
Icarus aiming,
Your suit in chaining,
You can choose to change it,
But the loose lips playing,
Your noose needs naming,
So you Analyse praying,
But you won't replace it,
Solution is basic,
on that parallel pacing,
No trap and chasing,
Facts mean payments,
Pragmat placing,
We not dogs ordaining,
PCG3
That's the code I'm playing`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/pcg3-cover.png"
  },
  {
    songNumber: 7,
    songName: "G3PP",
    description: "G3PP (Genesis 3 Paper Pushing) provides a surgical analysis of how Babylon's bureaucratic systems create Corrupted Recursive Loops. The track follows the psychological journey from innocent worker to corrupted oligarch.",
    linkToWebsite: "/surgical-analysis",
    lyrics: `INTRO:
Paper pushing pyrite pricks,
Chasing Fools gold tools old tryna find that fix,
In their chains is the life they live,
They keep their titles clipped,
On the boards they're like finite imps,
Isekaiing simps,
Professing worlds they would like to live,
Think that they'll change within,
They're not on the sadists sprint,
They pushing paper
To push paper,
That's the crimes they're in,
Externalities for mindless kin,

Act 1: PAPER PUSING WITH NO AGENCY

I'm just doing my job,
Tryna get my crop,
There's worse out there why would I ever lie off,
I'm not the one who signs off,
I'm the one who writes off,

ACT 2: CORRUPTED LOOP FORMING WANTING TO BECOME A FULL FLEDGED BABYLONIAN PLUTOCRAT/OLIGARCH/TECHNOFEUDALIST/ MEMETIC MAYA PROPAGANDIST/ BEAURACAT
Ladder must climb up,
Scent cashmeran the climb bot,
Seas just tide locked,
Seeds not my
The evil I lock,
In meeting my ops,
Have Eeking eye sores,
Like the regent rhinestones,
It's fake and final,
I seek more blindfolds,

ACT 3: CORRUPTED LOOP BECOMES CANIBALISING AND THEY SEE THEMSELVES AS A SUPERIOR VERISON OF HUMANITY PULLING PUPPET STRINGS OF THE POPULATION GETTING THEM TO THINK AND ACT IM WHATEVER WAYS THEY SEED. THE POPULATION ARE SEEN AS IDIOTS, THAT THEY NEED TO BE CONTROLLED, THE PAPER PUSHER IS DISGUSTED BY THEIR STUPIDITY AND THEIR WORSHIP OF IDOLS, IDEOLOGY, "LEADERS", BILLIONAIRE PROSPERITY PULPIT PREACHERS, BEARACRATS

More paper piezo,
Drown em in papers libel,
Sew suits of crime lords,
You fie foe fy fum,
We're feudal fight logged,
get rid of flight logs,
Let evil icons,
Get seeds of titles,
While we're the rightful,
Seed realms of kings and idols,
You serfs will cling to eyesores,
The greedful prideful,
Lustful libels,
Wrathful crimeful,
Now Zuck makes spiteful,
Divide conquer chirals,
Spin depressive spirals,
Stab wounds to vitals,
Clueless bitches,
Male or female,
With Dumb fuck details,
Send intellectual emails,
To clouds,
That we hail,
Ping pong ball mind,
Smooth no bump sight,
They call like Zanco,
Pay as you go,
See as you see,
Feed till you moult the creed no crew boats,
Push some paper,
To push for paper,
defines your labour
enrich your cagers

ACT 4: GENESIS ANAYLIS OF 5,000 YEAR BABYLON TAXONOMY, FEINING REVOLUTION STILL A DEEP SEATED HATRED BUT IT GETS TRANSMUTED TO OPERATIONAL NON-VIOLENT LOOPS

G3 Eyes see eyes that fright twitch,
Frozen sight glitch,
No mode not priming,
Primal climbing,
Same taxonomy,
Babylons Botany,
Bears fruits apocraphy,
Its accute dishonesty,
Feed that machine,
With bells and boom em,

ACT 5: GENESIS PARALLEL REPLY
Bun that,
G3 movement,
Biogas up,
Grid got backups,
Diesel biomes,
Bind their eyes closed,
Agents in clouds,
Got their mind in spirals,
Collapsing chirals,

Skyscrape Food Stock,
Bok Choy Bootings,
Water soothing,
Thats our cycle,
Leave greed and prideful,
The G3 genre,
Cant have no fakers,
 operational takers,
Not no tourists,
Back to babylons bullshit,
5 years of sight hope,
Now this is final,
No regent rhinestones,
Not regal either,
No kings no preachers,
G3PP on go now keep up.`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/g3pp-cover.png"
  },
  {
    songNumber: 8,
    songName: "Unclenching The White Grasp",
    description: "A technical analysis of the death realm and how Babylon's systems create spiritual and physical death. White Grasp exposes the mechanisms of control that operate through fear, greed, and ignorance, while showing how Genesis systems provide the tools for liberation.",
    linkToWebsite: "/esoteric-systems",
    lyrics: `That's the maiden by the water,
Leading lambs to slaughter,
In this realm there is no order,
Only murder end of quarter,
Pick the page of pocket pauper,
We know this book ain't got no author,
no sages saving slaughter,
It don't matter,
Son or daughter,
SCEP death is what they ordered
In your step you must be cautious,

You see I see militance, (PM)
they're blind and ignorant,
The time like sibiliance,
Slip stream similar,
Slits seams synergy,
The Realms just guilotines,
Been here since 17  BC,
Run by elites,

In tundras feel heat,
You plunge and release,
Your lungs now lead sleep,
Their function recede,
Got the dumper DP,
Your bumping Riri,
Shake the bumper cleanly,
Drink water Fiji,
Make the eyes look evil,
Look down on people,
Wear crowns so feeble,
Exercise with keegle,
MOE,
You put money over everything,
Now you FNP,
You don't feel no peace,
These thoughts are lethal
The law won't ease you
The thoughts are greedy,
The tourture TT,



That's the death realm president,
influences is evident,
Left clues in sediment,
They're oozing relevance,
Full of Void impediments,
He thinks he's poising medicine,
It's just raw memetics meant,
To morgue and measure you,
print paws of nephilim
And they're out here Jeklying,
Hyding,

Jester gesturing,
Podcast and let them in,
A farce of seraphim,
A class,
no elegance,
you don't know it but you've deemed divine,
All your CERL assigned,
Power of your life,
That's the meeker grind,
You can't see this time,
Cannot see the light,
You feel the fever fight,

But G3 can't save ya,
Give our tools to makers,
can't break 8 bill locks,
But can give you,
This is the white grasp spot,
Where the CERLS are God,
We just purge em off,
Get discernment on,
Cuz recursion costs,
So we burn em off,
G3 turn em off,
But there's the risk of infinite recursion,
With mixed assertions,
Don't loop there too long,
The death realm moves strings
Their Parasite pull strong,
Need you to stay on,
And manoeuvre root on,
Jump from loop to loop,
Break reform with truth,
See your worst rebuke,
The CERLS they'll lie with proof,
They try and bind the truth,
Make em blind and mute,
Diagnose acute,
Expose their crimes in loops,
Then build a loop,
Recur that truth,
Now be living proof,
And then take that proof,
Gotta load it up,
Close quarter shoot,
Walk em down boom em,
Now SCEP weapons build,
Now from across the map,
1000ft if that,
You one click,
One tap,
That's the pure collapse,
And it won't come back,
That how boom out pan,
Not in leisure land,
Leave em clueless pranged,
It's G3 in the Maker land X2
You cannot beat this plan,
We'll kill the seed of pan,
And then our creed will span,
It's the seed we ran,
None of meeker man,
Make the teachers land,
It's the feature man,


We see Peaceful Militance,
The seed is limitless,
Our creed is chilling in
We oh so realer than,
No bloat not Michelin,
And our mission mirrors it,
Protocol Parallel,
Poised and Patterning,
No recursive flattening,
Or glottonous fattening,
Boom through Pan,
That Clueless Hank,
Its PM we ain't losing land
G3 that's the movement man.
EM
Exponential Movement Man,
That's the movement man

Where the click at?
Ones that kick at,
With the BB blick at,
To bleed this mismatch
With means not figured,
On seas not hindered,
Their Sails got spinners,
Maybes rudder innerdards,
Need them PM willing,
The Stack want billing,
To collapse this in instance,
Incan engines,
With Ancient penchants,
The Labour renting,
The Sage ascending,
Now Mage relenting,
No saviour mentioned
With Sin tick synapse,
Not fin tick,
Tit tat,
Clinical cred at,
No Babylon bed at,
Need 'em savages said at,
Can manage their head at,
Preferable insanity sped at,
Then transmuted to ground it  lighting terra,
Your eyes see better
Under climate: pressure,
No pride is better,
No left right reader,
no acdem speakers,
No dirty leechers
These Pertinent features
Are for certain seekers,
Where boredoms reached us,
Now you tour the ether,
You see those leechers,
Extract, transmute then beam up,
CRL's dead those demons,


This here the beacon,
Prepare,
Don't ease up,
There's weight in creed up,
No saints no ego,
Need growers builders,
G3PP,
That's a certain feature
Can't have your curse as keeper,
Seen hearse not sleepers,
MDeath seeers,
Cant buy at kiosks,
Their eyes tranquilo,
But they got signs kilos,
Score weight like free throws,
No diet keto,
No lobotomy steelo,
Keys to Dichotomy keyholes,
With reach of the prophecy teetote,
You create your own,
See your own code,
Mode like solo,
Been on your dolo,
No doughnuts loco,
BBRL's non-existent hoe code,
Don't play polo,
Not in the mind of chrollo,
Hunter code tho,
PM proto,
Get that G3 mode on,
Install this codon,
Then go to infinity,
This the Recursive prologue
Turn the old off,
Get this code on,
Feature mode on,
Sages soul on,
Not saviour sewn on,
Passion logos,
To the atom sew on,
Protocol parallel,
These are our operative total,
Please make jokes with code on,
Or just dumb shit,
Have some fun prick,
This is how we're plunging,
Past Mariana,
To the mantle,
This that beacon,
Its what your scans pulled,
To Pillage that pan fool,
Cook and scramble,
There is no pre-amble,
G3PP,
No ontological tangles,`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/unclenching-white-grasp-cover.png"
  },
  {
    songNumber: 9,
    songName: "Memetic Archive_Aimless Routes Meet G3 Bout",
    description: "A dialogue between Babylon and Genesis systems, showing the fundamental incompatibility between their approaches. The track demonstrates how Genesis offers a superior alternative to Babylon's extraction-based economy.",
    linkToWebsite: "/why-genesis-wins",
    lyrics: `W.. W.. Will you sell out, X5
Look, your brain just fell out,
On The Aimless routes,
Fame and bread up,
Acclaim in leisure,
Pain beats pleasure,
Got it saved and treasured,
Idolatry fame unfettered,

So When you see your account
And you read the amount,
Is there a plea that you shout,
Try to reason it out,
All the steeze and the clout,
Are just fees in the cloud,
Lost your creed your a clown,
Pane circusese,
Bread and the circus,
Your soul ain't been murdered,
It just sneeks in motels,
And it's feeding of CERLS,
Quick cash for a swirl,
You think your riding the world,
But your a ride in this world,
Label, Bank, PE,
Don't matter,
whatever the greed sees,
It need needs,
Your just the ride that it's on,
Rent Out,
Push hard,
Then discard in due course,
Like Anakin they been mastered this force,
On their back ain't know target of course,
They fund the markers in law,
That's just a task to a corpse,
Stay in their crypt,
Speculate and play with their chips,

Babylon: Quick class them as poor,
In them larceny Courts,
Pull the legacy media strings,
We got the people fever pitching,
While their on that,
Pass some more bills,
We need subsidies still,
And a break from the tax,
And surveillance on tap,
Ain't no break can't relax,
Got the people in morgues,
If there's a chance they retort
And failing the farce of the laws,
Their are forces of tasks,
That will bang through your house,
Put you in camps,
We've got the Banks,
We've got the gov,
We've got the proof

G3: It's the G3 rebuke,
Cuz we stay looping the loops,
Can't be feeding their suits,
Waste is the prof,

Babylon: But your game has been lost,
The people don't favour the cage,
But a manger hath laid, debt and destruct,
Keep the voice down don't disrupt

G3: Your deranged disrespect,
How long have we sailed these seas,
Loop Econ,
Gold backed ON,
We got it where they solder strong,

Babylon: We must admit your code is strong,
But we are Babylon,
From the tales of old,
We pray to Owls made of stone,
We bought you, you and you

G3: You'll never see this through,
Don't know what the creed been through,
You left your money in bins,
I think it's funny your sins,
You don't know what muzzle you mint,
We'll just bun it up quick,
PM,
BPM,
Creed been sent,`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/memetic-archive-cover.png"
  },
  {
    songNumber: 10,
    songName: "Reloop Red Leash",
    description: "A warning about the dangers of violent revolution and the importance of peaceful militance. RED LEASH demonstrates how violent overthrow simply recreates the same power structures, while Genesis offers a superior path through operational non-violent loops.",
    linkToWebsite: "/genesis-protocol",
    lyrics: `*roar of a crowd*



With these leaders deposed,
I have ceceded their throne,
Their creed is evil in code,
They cannot feasibly sew,
Any seeds we have grown,
In their feverish tone,
They did plead for their bones,
To receive sins atoned,
I made em bleed in our code,
Their River flow through our roads,
And we target their skulls,
And we barred them from funds,
We are the harbinger ones
This is the Marxist memote,
In Libertarian coats
Much is after be sewn,
If you laugh at the tomes,
You will after be culled,
That is the charter we mould,
Makkakae crCrhskekeome,
Kill the targets with chrome,
You must bask in our cult,
What is there larger than loathe,
Keep disdain as your code,
We've destroyed and disowned,
Casted chains of their mode,
Broke the cage of their throes,
Those little larceny probes,
Pinching parts of our homes,
We had the right to depose,
Now the markets of old,
Replaced with classes unknown,


Got many targets with code,
but this charge he has thrown,
is but a clasp of this code,
You want to eat all the rich,
Or destroy all the libs,
It's a farce you will load,
Revving round crickets show,
You didn't master a code,
You just plastered your own,
Over targets chose,
You have your targets remote,
Now your charges are sewn,
You preach and pastor to Rome,
You yourself didn't change,
You've now repeated the phase,
This recursion replays,
It's played again and again,
Throughout the history chains,
Virtue pledging the same,
All disguised as a play,
To get the power seat saved,
Once you unsheath all the blades
With purpose system be slain,
Once it's crimson and stained,
And you have all the reins,
If your blade was once silver,
And you completed your game,
Now you have all the reins,
But you want to recind,
To the peaceful vision
Your crimson will remain,
Once you seize all the reins,
With gunpowder or blades,
You will rule just the same
Your old rulers remain,
All kinfolk of your blade,
Only know of the blade,
They have no building relay,
They're have not connected create,
So in their fury they rage,
Then they raze and they raze,
And the recursion replays,
And replays and replays,
You recreated a hell,
Just with code that you sew,
So scrap all of that,
Now i'm talking to you,
Take the peaceful militance suit,
No killing no brutes,
We build with repute,
Still have red leash in our suit,
But no CERL,
That is crude,
SRL from repute,
This is the Odyssey suit,
Golden fleeces is the fruit,
That this seed bears for you,
And for you and for you,
And for you and for you,
Its G3 in the suit,
Build your makers repute!`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/reloop-red-leash-cover.png"
  },
  {
    songNumber: 11,
    songName: "The Beacon",
    description: "A comprehensive analysis of how Babylon's structural poverty and systemic corruption lead to inevitable collapse. The Beacon documents the precise mechanisms of civilizational failure while showing how Genesis systems provide the only viable alternative.",
    linkToWebsite: "/collapse-protocol",
    lyrics: `Structural poverty,
The fattest of wallets with the most amount of property
Have the brokest of spirits,
they don't have autonomy
Puppets on strings,
Corpses control them improperly,
They fight and they bitch while they burn the economy,
Divide and distract,
Bread and circuses obviously,
The code they have brought is a code of dishonesty
Loathe and condition,
They'll flow into fission,
And they'll bring us all with em,
Now your locked up in prison,
Forked tongues never listen,
ICE'd out of the mission,
Deported there's schisms,
Lust,
Greed,
Wrath,
Pan the multipolar trap,
This one's corruption backed,
Let the game begin,
Who stay up wrought with sin,
Here's the condition for the win,
All your plans just put a pin,
Prop it up and plead with him,
Glorify all of the sin,
Add some pride to make you king,
That's a sight for many men,
They will die not rise again,
Here are leaders up above ,
They've got promises of love,
But it's all really been a bluff,
They only serve our  greed,
They have no covenant or creed,
Just a mandate can't reprieve,
You are serfs in comforts steed,
And when your on the bed of death,
The road to perdition is the realm you go to next,

I've been there,
Culture chase a check,
Watch your back you might be next,
He's coming for spot and he wants to steal your breath,
I was hopeless out of depth,
Out there just coasting on respect,
On the seas of Babylon,
I had no motion in my step,
Sipping the potion of oppressed,
No idea what to do next,
On the stillness of the sea,
I made a covenant and creed,
A loop economy I'll seed,
Pan to the left I see the greed,
On the right the treachery,
Behind I saw the succubus and it just waiting there for me,
It said you can't wait to break your creed,
It enticed me like the sirens of the sea,
And then I found the key,
There were agents in the clouds,
I saw their true purpose in the seas,
barriers of Babylon,
Hoards of knowledge they did seed,
And in that I saw my creed,
And then I saw the truth,
Where they used to speak,
The walls of babylon were mute,
The plan upon the covenant I made with myself was true,
A peaceful evolution building people of repute,
At land I said decentralise the root,
No single point of attack we build the people back from mute,
Silence the music of the flute,
And in that the pride was dead,
There is no king that's at the head,
If that decision was not made,
There would be nothing to respect,
Lay Genesis lockstep,

I do not hold with baited breath,
G3 Genesis will see to it that Babylon is dead,
And in its place is our stead`,
    audioFile: "/audio/G3PP - EM - SoundLoadMate.com.mp3",
    coverArt: "/images/cover-art/the-beacon-cover.png"
  }
];
