[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"

# Handle client-side routing for Next.js static export
# Note: trailingSlash is set to false in next.config.js, so no redirects needed

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/audio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Additional configuration for static site
[build.processing]
  skip_processing = false

# Form handling (for future contact forms)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Edge functions (for future API routes)
# [functions]
#   directory = "netlify/functions"
